[package]
name = "gameserv"
version = "0.1.0"
authors = ["Victor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0-beta"
actix = "0.9.0"
actix-web-actors = "2"
